[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
noir_analyzer = { path = "../noir_analyzer" }
nargo = { workspace = true }